--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 17.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: transaction_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.transaction_type_enum AS ENUM (
    'EINZAHLUNG',
    'AUSZAHLUNG',
    'UEBERWEISUNG'
);


--
-- Name: transactiontype; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.transactiontype AS ENUM (
    'AUSZAHLUNG',
    'EINZAHLUNG',
    'UEBERWEISUNG'
);


--
-- Name: CAST (public.transactiontype AS character varying); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (public.transactiontype AS character varying) WITH INOUT AS IMPLICIT;


--
-- Name: CAST (character varying AS public.transactiontype); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (character varying AS public.transactiontype) WITH INOUT AS IMPLICIT;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: direct_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.direct_messages (
    id bigint NOT NULL,
    sender bigint NOT NULL,
    recipient bigint NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE direct_messages; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.direct_messages IS 'Direct messages between two users.';


--
-- Name: direct_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.direct_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.direct_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pinboard_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pinboard_comments (
    id bigint NOT NULL,
    wall_owner_id bigint NOT NULL,
    author_id bigint,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE pinboard_comments; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.pinboard_comments IS 'Comments on user pinboards (owner vs. author).';


--
-- Name: pinboard_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pinboard_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pinboard_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    transaction_type public.transaction_type_enum NOT NULL,
    amount numeric(12,2) NOT NULL,
    sender bigint,
    recipient bigint,
    description character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT transactions_amount_positive_chk CHECK ((amount > (0)::numeric)),
    CONSTRAINT transactions_type_semantics_chk CHECK ((((transaction_type = 'EINZAHLUNG'::public.transaction_type_enum) AND (sender IS NULL) AND (recipient IS NOT NULL)) OR ((transaction_type = 'AUSZAHLUNG'::public.transaction_type_enum) AND (sender IS NOT NULL) AND (recipient IS NULL)) OR ((transaction_type = 'UEBERWEISUNG'::public.transaction_type_enum) AND (sender IS NOT NULL) AND (recipient IS NOT NULL) AND (sender <> recipient))))
);


--
-- Name: TABLE transactions; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.transactions IS 'Journal of all monetary movements (EINZAHLUNG, AUSZAHLUNG, UEBERWEISUNG).';


--
-- Name: COLUMN transactions.transaction_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.transactions.transaction_type IS 'EINZAHLUNG | AUSZAHLUNG | UEBERWEISUNG (enforced by CHECK).';


--
-- Name: COLUMN transactions.amount; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.transactions.amount IS 'Positive amount (NUMERIC(12,2)).';


--
-- Name: COLUMN transactions.sender; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.transactions.sender IS 'FK users.id; NULL for EINZAHLUNG, set for AUSZAHLUNG/UEBERWEISUNG.';


--
-- Name: COLUMN transactions.recipient; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.transactions.recipient IS 'FK users.id; NULL for AUSZAHLUNG, set for EINZAHLUNG/UEBERWEISUNG.';


--
-- Name: COLUMN transactions.description; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.transactions.description IS 'Free text/description (CSV: "Beschreibung").';


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username character varying(320) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT users_username_lowercase_chk CHECK (((username)::text = lower((username)::text)))
);


--
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.users IS 'Registered users. username is email (lowercase, unique).';


--
-- Name: COLUMN users.username; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.username IS 'Email address, lowercase. Unique.';


--
-- Name: COLUMN users.password_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.password_hash IS 'Password hash (e.g., Argon2id/bcrypt).';


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: direct_messages direct_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.direct_messages
    ADD CONSTRAINT direct_messages_pkey PRIMARY KEY (id);


--
-- Name: pinboard_comments pinboard_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pinboard_comments
    ADD CONSTRAINT pinboard_comments_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_unique_ci; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_unique_ci UNIQUE (username);


--
-- Name: users users_username_uq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_uq UNIQUE (username);


--
-- Name: dm_pair_ctime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dm_pair_ctime ON public.direct_messages USING btree (LEAST(sender, recipient), GREATEST(sender, recipient), created_at);


--
-- Name: dm_recipient_ctime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dm_recipient_ctime ON public.direct_messages USING btree (recipient, created_at);


--
-- Name: dm_sender_ctime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dm_sender_ctime ON public.direct_messages USING btree (sender, created_at);


--
-- Name: pb_author_ctime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pb_author_ctime ON public.pinboard_comments USING btree (author_id, created_at);


--
-- Name: pb_owner_ctime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pb_owner_ctime ON public.pinboard_comments USING btree (wall_owner_id, created_at);


--
-- Name: trx_recipient_ctime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trx_recipient_ctime ON public.transactions USING btree (recipient, created_at);


--
-- Name: trx_recipient_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trx_recipient_idx ON public.transactions USING btree (recipient);


--
-- Name: trx_sender_ctime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trx_sender_ctime ON public.transactions USING btree (sender, created_at);


--
-- Name: trx_sender_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trx_sender_idx ON public.transactions USING btree (sender);


--
-- Name: direct_messages direct_messages_recipient_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.direct_messages
    ADD CONSTRAINT direct_messages_recipient_fkey FOREIGN KEY (recipient) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: direct_messages direct_messages_sender_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.direct_messages
    ADD CONSTRAINT direct_messages_sender_fkey FOREIGN KEY (sender) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: pinboard_comments pinboard_comments_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pinboard_comments
    ADD CONSTRAINT pinboard_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: pinboard_comments pinboard_comments_wall_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pinboard_comments
    ADD CONSTRAINT pinboard_comments_wall_owner_id_fkey FOREIGN KEY (wall_owner_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: transactions transactions_recipient_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_recipient_fkey FOREIGN KEY (recipient) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: transactions transactions_sender_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_sender_fkey FOREIGN KEY (sender) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

